version: '2'
services:
  zookeeper:
    image: zookeeper:3.4
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper:2888:3888

  mesos-master:
    image: mesosphere/mesos-master:1.2.1
    restart: always
    network_mode: "host"
    environment:
      - MESOS_CLUSTER=MESOS
      - MESOS_HOSTNAME=101.132.47.61
      - MESOS_IP=172.19.25.220
      - MESOS_ZK=zk://172.19.25.220:2181/mesos
      - MESOS_PORT=5050
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos
    volumes:
      - "./log/mesos:/var/log/mesos"
      - "./tmp/mesos:/var/tmp/mesos"
    depends_on:
      - zookeeper

  mesos-slave:
    image: mesosphere/mesos-slave:1.2.1
    restart: always
    network_mode: "host"
    environment:
      - MESOS_HOSTNAME=101.132.47.61
      - MESOS_IP=172.19.25.220
      - MESOS_LAUNCHER=posix
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://172.19.25.220:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - "./log/mesos:/var/log/mesos"
      - "./tmp/mesos:/var/tmp/mesos"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cgroup:/cgroup"
      - "/sys:/sys"
      - "/usr/local/bin/docker:/usr/local/bin/docker"
    privileged: true
    depends_on:
      - zookeeper

  marathon:
    image: mesosphere/marathon:v1.4.7
    restart: always
    ports:
      - "8080:8080"
    entrypoint: ./bin/start --master zk://172.19.25.220:2181/mesos --zk zk://172.19.25.220:2181/marathon

  consul:
    image: consul:0.9.2
    restart: always
    ports:
      - "8500:8500"

